config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root 'welcome#index'
  get 'dashboard/index'

  resources :transactions, only: [:show, :index, :create, :new]
  resources :customers do
    resources :transactions, only: [:show, :index, :create, :new]
    member do
      patch 'update_omise_cards'
    end
  end

  constraints subdomaion: 'api'do
    scope module: 'api', defaults: {format: :json} do
      namespace :v1 do
        resources :customers
      end
    end
  end


  devise_for :user

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include OmiseApi
  has_many :transactions

  after_create :create_omise_customer
  after_update :update_omise_customer
  after_destroy :destroy_omise_customer

  validates :email, uniqueness: true

  def create_omise_customer
    omise_customer = omise_api.create_customer({description: "#{self.first_name} #{self.last_name}", email: self.email})
    self.omise_customer_id = omise_customer['id']
    self.save!
  end

  def update_omise_customer
    omise_api.update_customer(self.omise_customer_id, {description: "#{self.first_name} #{self.last_name}", email: self.email})
  end

  def destroy_omise_customer
    omise_api.delete_customer(self.omise_customer_id)
  end

end

app/controllers/api/v1/customers_controller.rb
module Api::V1
  class CustomersController < ApiController
    before_action :set_customer, only: [:show, :edit, :update, :destroy, :update_omise_cards]

    # GET /customers
    # GET /customers.json
    def index
      @customers = Customer.all
    end

    # GET /customers/1
    # GET /customers/1.json
    def show
    end

    # GET /customers/new
    def new
      @customer = Customer.new
    end

    # GET /customers/1/edit
    def edit
    end

    # POST /customers
    # POST /customers.json
    def create
      @customer = Customer.new(customer_params)

      respond_to do |format|
        if @customer.save
          format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
          format.json { render :show, status: :created, location: @customer }
        else
          format.html { render :new }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /customers/1
    # PATCH/PUT /customers/1.json
    def update
      respond_to do |format|
        if @customer.update(customer_params)
          format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
          format.json { render :show, status: :ok, location: @customer }
        else
          format.html { render :edit }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /customers/1
    # DELETE /customers/1.json
    def destroy
      @customer.destroy
      respond_to do |format|
        format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    # Update card for customer
    def update_omise_cards
      card = params.require(:customer).permit(:card)
      omise = SampleOmise.omise_api
      omise_customer = omise.update_customer(@customer.omise_customer_id, card)
      @omise_card = omise_customer['cards']['data'].last
      respond_to do |format|
        format.json { render json: @omise_card.to_json, status: :ok }
      end

    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email)
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy, :update_omise_cards]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    omise_api = SampleOmise.omise_api
    @omise_customer = omise_api.get_customer(@customer.omise_customer_id)
    @cards = @omise_customer['cards']['data']
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Update card for customer
  def update_omise_cards
    card = params.require(:customer).permit(:card)
    omise = SampleOmise.omise_api
    omise_customer = omise.update_customer(@customer.omise_customer_id, card)
    @omise_card = omise_customer['cards']['data'].last
    respond_to do |format|
      format.json {render json: @omise_card.to_json, status: :ok }
    end

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.slim
= form_for(@customer) do |f|
  - if @customer.errors.any?
    #error_explanation
      h2
        = pluralize(@customer.errors.count, "error")
        |  prohibited this transaction from being saved:
      ul
        - @customer.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'
  .form-group
    = f.submit 'Create New Customer', class: 'btn btn-primary'

app/views/customers/edit.html.slim
h1
  | Editing Customer
= render 'form'
= link_to 'Show', @customer
|  | 
= link_to 'Back', customers_path

app/views/customers/index.html.slim
p#notice
  = notice
table.table
  thead
    tr
      th
        | First Name
      th
        | Last Name
      th
        | Email
      th[colspan='4']
  tbody
    - @customers.each do |customer|
      tr
        td
          == customer.first_name
        td
          == customer.last_name
        td
          == customer.email
        td
          == link_to "List transactions (#{customer.transactions.size})", customer_transactions_path(customer)
        td
          == link_to 'Show', customer
        td
          == link_to 'Edit', edit_customer_path(customer)
        td
          == link_to 'Destroy', customer, method: :delete, data: {confirm: 'Are you sure?'}
br
== link_to 'New customer', new_customer_path

app/views/customers/new.html.slim
h1
  | New Customer
= render 'form'
= link_to 'Back', customers_path

app/views/customers/show.html.slim
p#notice
  = notice
p
  strong
    | First Name:
  = @customer.first_name
p
  strong
    | Last Name:
  = @customer.last_name
p
  strong
    | Email:
  = @customer.email
h1
  | List Cards
= react_component('ListCardsComponent', cards: @cards, customer_id: @customer.id)

= link_to 'Edit', edit_customer_path(@customer)
|  | 
= link_to 'Back', customers_path