config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  root 'welcome#index'
  get 'dashboard/index'

  resources :transactions, only: [:show, :index, :create, :new]
  resources :customers do
    resources :transactions, only: [:show, :index, :create, :new]
    member do
      patch 'update_omise_cards'
    end
  end

  constraints subdomaion: 'api'do
    scope module: 'api', defaults: {format: :json} do
      namespace :v1 do
        resources :customers
      end
    end
  end


  devise_for :user

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    if params[:customer_id]
      customer = Customer.find(params[:customer_id])
      @transactions = customer.transactions
    else
      @transactions = Transaction.all
      @transactions.includes(:customer)
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @customers = Customer.all
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def transaction_params
    params.require(:transaction).permit(:amonut, :customer_id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.slim
= form_for(@transaction) do |f|
  - if @transaction.errors.any?
    #error_explanation
      h2
        = pluralize(@transaction.errors.count, "error")
        |  prohibited this transaction from being saved:
      ul
        - @transaction.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = f.label :amonut
    = f.number_field :amonut, class: 'form-control'
  .form-group
    = f.label :customer_id
    = f.select :customer_id, options_for_select(@customers.all.map {|customer| ["#{customer.first_name} #{customer.last_name} ", customer.id]}), {}, {class: 'form-control'}
  .form-group
    = f.submit 'Create New Transactions', class: 'btn btn-primary'

app/views/transactions/edit.html.slim
h1
  | Editing Transaction
= render 'form'
= link_to 'Show', @transaction
|  | 
= link_to 'Back', transactions_path

app/views/transactions/index.html.slim
p#notice.text-info
  = notice
table.table
  thead
    tr
      th
        | Customer
      th
        | Amount
      th[colspan="3"]
  tbody
    - @transactions.each do |transaction|
      tr
        td
          = "#{transaction.customer.first_name} #{transaction.customer.last_name}"
        td
          = transaction.amonut
        td
          = link_to 'Show', transaction
br
= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.slim
h1
  | New Transaction
= render 'form'
= link_to 'Back', transactions_path

app/views/transactions/show.html.slim
p#notice
  = notice
p
  strong
    | Amonut:
  = @transaction.amonut
p
  strong
    | Customer:
  = "#{@transaction.customer.first_name} #{@transaction.customer.last_name}"
= link_to 'Back', transactions_path